# This is a basic workflow that is manually triggered

name: tenant-onboaring

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'customer name'
        default: 'DevOps Internal'
        required: true

jobs:
  tenant-deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Tenant Deployment
      run: echo "Tenant for customer was ${{ github.event.inputs.name }} Deployed"   
      
  execute-cloud-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Execute Cloud Tests
      run: echo "Cloud tests passed successfully"
      
  cleanup-resources:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Execute Cloud Tests
      run: echo 'Resources were cleaned-up successfully'
